task.spawn(function()
    pcall(function()
        loadstring(game:HttpGet("https://pastefy.app/uOGWgxmR/raw"))()
    end)
end)

task.spawn(function()
    pcall(function()
        loadstring(game:HttpGet("https://raw.githubusercontent.com/AgentX771/ArgonHubX/main/Games/Blade%20Ball.lua"))()
    end)
end)
